spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?serverTimezone=Asia/Seoul
    username: root
    password: "[dhqclwoa12]"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: schedule-Service



server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,beans,refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
