spring:
  application:
    name : BAND-SCHEDULE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?serverTimezone=Asia/Seoul
    username: root
<<<<<<< HEAD
    password: 1234
=======
    password: 1q2w3e4r!!
>>>>>>> e4d95cb2ef269b79b090295107ab86f7013c779f
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

